//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshLawn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_email
    {
        public long id { get; set; }
        public string sender { get; set; }
        public string recipient { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
        public int status { get; set; }
        public bool is_office { get; set; }
    }
}
